version: '3'

services:
  db:
    image: postgres:16-alpine
    environment:
      LANG: fr_FR.utf8
      POSTGRES_INITDB_ARGS: --locale-provider=icu --icu-locale=fr-FR
      POSTGRES_PASSWORD: toto
    volumes:
      - .:/sql
      - db:/var/lib/postgresql/data
  
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080

volumes:
  db:
