version: '3'

services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=toto
    volumes:
      - .:/sql
  
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
