version: '3.8'

services:
  db:
    image: mariadb:10.9.3
    volumes:
      - ./database:/var/lib/mysql:Z
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: database

  phpmyadmin:
    image: phpmyadmin:5.2.0
    ports:
      - 8081:80

  adminer:
    image: adminer:4.8.1
    ports:
      - 8080:8080
