version: '3.8'

services:
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf 
      - ./:/src

  php:
    image: php:fpm
    volumes:
      - ./:/src

  composer:
    image: composer
    entrypoint: composer
    volumes:
      - ./:/app
    
  npm:
    image: node:lts
    volumes:
      - ./:/usr/app
    working_dir: /usr/app
    entrypoint: npm

